# Unique identifier for considered sensors. 
string          sensor1
string          sensor2

# Global correlation score
float32         global_score

# Inter-centers distance
float32         distance

# Bounding box IoU correlation score
float32         iou_score
float32         iou_coef

# Velocity correlation score
float32         velocity_score
float32         velocity_coef

# Classification correlation score
float32         classification_score
float32         classification_coef
